services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=172.20.0.7:5432
      - TRUSTED_PROXIES=172.20.0.2
      - OVERWRITECONDADDR=^172\.20\.0\.2$
      - OVERWRITEWEBROOT=
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=nextcloud.${MAIN_DOMAIN_NAME}
      - OVERWRITECLIURL=https://nextcloud.${MAIN_DOMAIN_NAME}
    volumes:
      - ./data:/var/www/html
    networks:
      traefik:
        ipv4_address: 172.20.0.6

networks:
  traefik:
    name: traefik
    external: true
