http:
  routers:
    landing:
      entryPoints: web-secure
      rule: Host(`{{env "MAIN_DOMAIN_NAME"}}`) || Host(`www.{{env "MAIN_DOMAIN_NAME"}}`)
      service: landing
      middlewares: www-redirect@file
      tls:
        certresolver: letsencrypt
        domains:
          - main: '{{env "MAIN_DOMAIN_NAME"}}'
            sans: www.{{env "MAIN_DOMAIN_NAME"}}
  services:
    landing:
      loadBalancer:
        servers:
          - url: http://172.20.0.5:3000/
