http:
  routers:
    nextcloud:
      entryPoints: https
      rule: Host(`nextcloud.{{env "MAIN_DOMAIN_NAME"}}`) || Host(`www.nextcloud.{{env "MAIN_DOMAIN_NAME"}}`)
      service: nextcloud
      middlewares: 
        - www-redirect@file
        - nextcloud-well-known-redirect
        - nextcloud-headers
      tls:
        certresolver: letsencrypt
        domains:
          - main: nextcloud.{{env "MAIN_DOMAIN_NAME"}}
            sans: www.nextcloud.{{env "MAIN_DOMAIN_NAME"}}
  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: http://172.20.0.6:80/

  middlewares:
    nextcloud-well-known-redirect:
      redirectRegex:
        permanent: true
        regex: https://(.*)/.well-known/(?:card|cal)dav
        replacement: https://${1}/remote.php/dav
    nextcloud-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: https
        hostsProxyHeaders: X-Forwarded-Host
        contentSecurityPolicy: upgrade-insecure-requests
        referrerPolicy: same-origin
