api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  web-secure:
    address: :443
  drawpile:
    address: :27750
  wireguard:
    address: :51820/udp

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  letsencrypt:
    acme:
      # Uncomment if testing something that could lead to many requests
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: acme.json
      httpChallenge:
        entryPoint: web

providers:
  file:
    directory: /etc/traefik
    watch: true

log:
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log
