http:
  routers:
    wireguard-frontend:
      entryPoints: web-secure
      rule: Host(`wireguard.{{env "MAIN_DOMAIN_NAME"}}`) || Host(`www.wireguard.{{env "MAIN_DOMAIN_NAME"}}`)
      service: wireguard-frontend
      middlewares: www-redirect@file
      tls:
        certresolver: letsencrypt
        domains:
          - main: wireguard.{{env "MAIN_DOMAIN_NAME"}}
            sans: www.wireguard.{{env "MAIN_DOMAIN_NAME"}}
  services:
    wireguard-frontend:
      loadBalancer:
        servers:
          - url: http://172.20.0.4:51821/

udp:
  routers:
    wireguard:
      entryPoints: wireguard
      service: wireguard
  services:
    wireguard:
      loadBalancer:
        servers:
          - address: 172.20.0.4:51820
