services:
  videoroom:
    build: .
    container_name: videoroom
    restart: unless-stopped
    networks:
      traefik:
        ipv4_address: 172.20.0.12

networks:
  traefik:
    name: traefik
    external: true
