services:
  traefik:
    container_name: landing
    restart: unless-stopped
    volumes:
      - ./src:/etc/landing
    networks:
      traefik:
        ipv4_address: 172.20.0.5

networks:
  traefik:
    name: traefik
    external: true
