services:
  landing:
    build: .
    container_name: landing
    restart: unless-stopped
    networks:
      traefik:
        ipv4_address: 172.20.0.5

networks:
  traefik:
    name: traefik
    external: true
