services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wireguard
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LANG=${LANG}
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=${PASSWORD_HASH}
      - PORT=51821
      - WG_PORT=51820
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - ./config:/etc/wireguard
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      traefik:
        ipv4_address: 172.20.0.4

networks:
  traefik:
    name: traefik
    external: true
